### ISSUE TITLE
Python 3 support on Travis

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#44]
The only remaining problem is installing Python 3, and discovering an `apt-get install` of PyQt4.

- [Travis log of problem](https://travis-ci.org/mottosso/Qt.py/jobs/134575335)
- [`.travis.yml` at point of log](https://github.com/abstractfactory/Qt.py/blob/54dc33e41900fb55691e9deb2c6d1b5471c7558d/.travis.yml)

How can we install Python 3 and gain access to a system-wide install of PyQt4?

**Comment by fredrikaverpil** [comment]
I haven't used it myself at all, but could possible [Anaconda](https://www.continuum.io/downloads) help out here?

**Comment by mottosso** [comment]
No I don't think so, Travis is running each Python distrubution in it's own "container", so there only ever is a single version of Python available.

It's Travis specific, in that it establishes a virtual environment in each container, and this environment doesn't have access to system packages. It's the equivalent of this.

```python
$ virtualenv myenv
# Windows
$ myenv/Scripts/activate.bat
# Linux
$ . myenv/bin/activate
```

So when we then go `apt-get install python-qt4`, then PyQt4 is installed amongst system wide `site-packages` which is invisible to this environment.

What will have to happen, I think, is to copy/symlink the system install into the virtualenv so that it gains has access to it.

You can play around with it, simply modify `.travis.yml` and make a PR. Add `3.4` to the `python:` key and Travis will try and build it. You could also try and setup this environment locally in a Docker container and try and capture the problem there.

**Comment by fredrikaverpil** [comment]
I see. I've postponed looking into Travis CI for Github repos for so long now. It's high time for me to set time aside for this, not only for this project.

Just to see that it indeed installed PyQt4, we could try executing this:

    python -c "import sys;sys.path.append('/path/to/site-packages/')import PyQt4;print(PyQt4)"

But since PyQt (PyQt4) won't install via pip, it seems we need to resort to building it which is quite time consuming. A faster approach could be to install a pre-compiled version through Anaconda:

    conda install pyqt

I'll spin up a Ubuntu 12.04 container and try this.

By the way, did you lock down the environment to Ubuntu 12.04 or is this done automatically by Travis? (just curious)

**Comment by fredrikaverpil** [comment]
[Here's](http://stackoverflow.com/questions/35513019/install-pyqt4-with-python3-on-travis-ci) also something which the author claims to be working:

```yaml
language: python
python:
  - "3.5"
before_install:
    - sudo mkdir -p /downloads
    - sudo chmod a+rw /downloads
    - curl -L http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz -o /downloads/sip.tar.gz 
    - curl -L http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz -o /downloads/pyqt4.tar.gz
    # Builds
    - sudo mkdir -p /builds
    - sudo chmod a+rw /builds

install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get install -y libqt4-dev
    - sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
#    - sudo apt-get install -y python3-sip python3-sip-dev python3-pyqt4 cmake
    # Qt4
    - pushd /builds
    # SIP
    - tar xzf /downloads/sip.tar.gz --keep-newer-files
    - pushd sip-4.16.5
    - python configure.py
    - make
    - sudo make install
    - popd
    # PyQt4
    - tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
    - pushd PyQt-x11-gpl-4.11.3
    - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtTest
    - make
    - sudo make install
    - popd
    # Builds Complete
    - popd
    - pip install -r requirements.txt
```
